/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard-layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as CanvasStoryIdRouteImport } from './routes/canvas.$storyId'
import { Route as LayoutSignupRouteImport } from './routes/_layout/signup'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as DashboardLayoutDashboardRouteImport } from './routes/_dashboard-layout/dashboard'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const CanvasStoryIdRoute = CanvasStoryIdRouteImport.update({
  id: '/canvas/$storyId',
  path: '/canvas/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSignupRoute = LayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const DashboardLayoutDashboardRoute =
  DashboardLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/profile': typeof ProfileRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/login': typeof LayoutLoginRoute
  '/signup': typeof LayoutSignupRoute
  '/canvas/$storyId': typeof CanvasStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/profile': typeof ProfileRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/login': typeof LayoutLoginRoute
  '/signup': typeof LayoutSignupRoute
  '/canvas/$storyId': typeof CanvasStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard-layout': typeof DashboardLayoutRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/profile': typeof ProfileRoute
  '/_dashboard-layout/dashboard': typeof DashboardLayoutDashboardRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/signup': typeof LayoutSignupRoute
  '/canvas/$storyId': typeof CanvasStoryIdRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/profile' | '/dashboard' | '/login' | '/signup' | '/canvas/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/profile' | '/dashboard' | '/login' | '/signup' | '/canvas/$storyId'
  id:
    | '__root__'
    | '/_dashboard-layout'
    | '/_layout'
    | '/profile'
    | '/_dashboard-layout/dashboard'
    | '/_layout/login'
    | '/_layout/signup'
    | '/canvas/$storyId'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  CanvasStoryIdRoute: typeof CanvasStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard-layout': {
      id: '/_dashboard-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/canvas/$storyId': {
      id: '/canvas/$storyId'
      path: '/canvas/$storyId'
      fullPath: '/canvas/$storyId'
      preLoaderRoute: typeof CanvasStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/signup': {
      id: '/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_dashboard-layout/dashboard': {
      id: '/_dashboard-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutDashboardRoute: typeof DashboardLayoutDashboardRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutDashboardRoute: DashboardLayoutDashboardRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface LayoutRouteChildren {
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutSignupRoute: typeof LayoutSignupRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutSignupRoute: LayoutSignupRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  ProfileRoute: ProfileRoute,
  CanvasStoryIdRoute: CanvasStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
